import { NextResponse } from "next/server";

export async function GET(req) {
  if (req.method === "GET") {
    const data = [
      "Agen Gas Elpiji",
      "Apartemen Hotel / Service Apartemen / Kondominium Hotel",
      "Apotek",
      "Arena Permainan",
      "ATM Drive-Thru",
      "Balai Warga",
      "Bandara Khusus",
      "Bandara Umum",
      "Bangunan Agen Kurir",
      "Bangunan Analis dan Uji Teknis",
      "Bangunan Industri Kecil",
      "Bangunan Industri Menengah dan Besar",
      "Bangunan Industri Menengah dan Besar (Bangunan)",
      "Bangunan Instalasi Energi",
      "Bangunan Jasa Penerbitan",
      "Bangunan Katering",
      "Bangunan Kepolisian",
      "Bangunan Ketenaganukliran",
      "Bangunan Kurir/Pos",
      "Bangunan Pelayanan Penunjang Kesehatan",
      "Bangunan Pencucian dan Salon Kendaraan Bermotor",
      "Bangunan Pendidikan Anak Usia Dini",
      "Bangunan Pendidikan Dasar dan Menengah",
      "Bangunan Pendidikan Tinggi",
      "Bangunan Penelitian dan Pengembangan Ilmu",
      "Bangunan Pengobatan Alternatif/ Tradisional",
      "Bangunan Pengolahan Air Bersih",
      "Bangunan Pengolahan Air Limbah",
      "Bangunan Pengolahan Air Limbah B3",
      "Bangunan Penitipan Anak (Daycare)",
      "Bangunan Penitipan Hewan (Pet Shop)",
      "Bangunan Penyediaan Jasa Perorangan Untuk Kebugaran Bukan Olahraga",
      "Bangunan Peternakan",
      "Bangunan Pusat Data (Data Center)",
      "Bangunan Saringan Sampah",
      "Bangunan TNI AD",
      "Bangunan TNI AL",
      "Bangunan TNI AU",
      "Bangunan Untuk Aktivitas Pertambangan",
      "Bangunan Untuk Penyewaan Alat Konstruksi",
      "Bank Sampah",
      "Batching Plant",
      "Bengkel",
      "Binatu/ Laundry",
      "Bioskop",
      "Budidaya Perikanan Air Laut",
      "Budidaya Perikanan Air Tawar",
      "Bumi Perkemahan / Taman Karavan",
      "Daur Ulang",
      "Departement Store / Pusat Perbelanjaan",
      "Depo Amunisi",
      "Dermaga Penyeberangan",
      "Drainase",
      "Fasilitas Gelanggang / Arena",
      "Fasilitas Pemadam Kebakaran",
      "Fasilitas Pengolahan Sampah Antara (FPSA)",
      "Fasilitas Sirkuit",
      "Game Center",
      "Gedung Kesenian",
      "Gedung Olahraga",
      "Gedung Serba Guna",
      "Gelanggang Renang",
      "Gereja",
      "Guest House/Rumah Kos",
      "Helipad",
      "Homestay",
      "Hotel",
      "Hutan Kota",
      "Hutan Produksi",
      "Hypermarket",
      "Industri Mikro",
      "Jalan",
      "Jaringan Perpipaan",
      "Jaringan Serat Optik",
      "Jasa Pemakaman",
      "Jembatan",
      "Kafe/ Kedai Minuman",
      "Kantor dan Bisnis Profesional",
      "Kantor Lembaga Keuangan",
      "Kantor Yayasan/Organisasi Kemasyarakatan",
      "Karaoke",
      "Kebun Binatang",
      "Kedai Obat Tradisional/ Jamu",
      "Kelab Malam, Diskotik, Bar, Pub",
      "Kelenteng",
      "Klinik Hewan",
      "Klinik Pratama",
      "Klinik Utama",
      "Kolam Pemancingan",
      "Pemancingan",
      "Kolam Retensi / Waduk / Situ / Embung / danau",
      "Koperasi",
      "Laboratorium Forensik",
      "Laboratorium Kesehatan",
      "Lapangan Olahraga",
      "Marina",
      "Masjid",
      "Mercusuar",
      "Minimarket",
      "Multifungsi (Mixed-Use)",
      "Museum",
      "Musholla",
      "Padang Golf dan Arena Latihan Golf",
      "Pangkalan Penjualan Bbm dan Gas Elpiji",
      "Panti Sosial",
      "Parkir Kendaraan Berat",
      "Parkir Kendaraan Bermotor",
      "Parkir Sepeda",
      "Pasar Rakyat",
      "Patung dan/atau Tugu",
      "Pelabuhan Laut",
      "Pelabuhan Perikanan",
      "Pemakaman",
      "Pembangkit Tenaga Listrik",
      "Penangkapan Hewan",
      "Penangkaran Hewan yang Dilindungi",
      "Pendidikan Pelatihan / Kursus",
      "Pergudangan dan Penyimpanan Terbuka",
      "Pergudangan dan Penyimpanan Tertutup",
      "Perikanan Tangkap",
      "Perkantoran Pemerintahan",
      "Perkantoran Perwakilan Negara Asing",
      "Perpustakaan dan Arsip",
      "Pertanian/Perkebunan",
      "Pertokoan",
      "Pesantren",
      "Pintu Air",
      "Pondok Wisata / Cottage",
      "Pool Kendaraan Berat",
      "Pool Kendaraan Ringan",
      "Pos Penjagaan Keamanan",
      "Pos Polisi",
      "Praktek Dokter  (Umum, Gigi, Spesialis) / Bidan",
      "Pura",
      "Pusat Jajan",
      "Pusat Kebugaran / Fitness Center",
      "Pusat Kegiatan Keagamaan",
      "Pusat Transmisi dan Pemancar Jaringan Telekomunikasi",
      "Puskesmas",
      "Reklame",
      "Rel",
      "Resort Apung",
      "Resort Wisata",
      "Restoran",
      "Ruang Pamer/Exhibition",
      "Rumah Dinas",
      "Rumah Flat",
      "Rumah Pompa",
      "Rumah Sakit",
      "Rumah Sakit/Pusat Kesehatan Hewan",
      "Rumah Susun Khusus",
      "Rumah Susun Komersial",
      "Rumah Susun Negara",
      "Rumah Susun Umum",
      "Rumah Tapak",
      "Sektor Usaha Informal Makanan dan Minuman",
      "Sektor Usaha Informal Selain Makanan dan Minuman",
      "Showroom Kendaraan Bermotor",
      "SKTT, SKTM, SKTR",
      "SPBU/ SPBG",
      "SPKLU dan SPBKLU",
      "Stadion",
      "Stasiun",
      "Stasiun Pemantau Kualitas Udara Ambien",
      "Studio Keterampilan",
      "Sumur",
      "Taman",
      "Taman Budaya / Teater Terbuka",
      "Taman Hiburan atau Taman Rekreasi",
      "Taman Konservasi Alam",
      "Taman Laut",
      "Taman Wisata Alam",
      "Tanggul",
      "Tempat Pelelangan Ikan",
      "Tempat Pemotongan Hewan",
      "Tempat Pemrosesan Akhir (TPA)",
      "Tempat Penampungan Sementara (TPS)",
      "Tempat Penampungan Sementara B3 (TPS B3)",
      "Tempat Pengolahan Sampah Dengan Prinsip Reduce, Reuse, Recycle (TPS-3R)",
      "Tempat Pengolahan Sampah Terpadu (TPST)",
      "Terminal",
      "Terowongan/Gorong-Gorong/Tunnel",
      "Toko Bahan dan Perlengkapan Bangunan",
      "Toko Besar",
      "Toko Eceran Makanan/Bahan Makanan dan Minuman",
      "Toko Eceran Selain Makanan dan Minuman",
      "Toko Swalayan",
      "Transport Shuttle",
      "Vihara",
      "Vila",
      "Warung Internet dan Warung Telekomunikasi",
      "Warung Makan",
      "Wisata Agro",
      "Wisata Agro (Bangunan)",
    ];
    return NextResponse.json({ data }, { status: 200 });
  }
}
