import { NextResponse } from "next/server";

export async function GET(req) {
  if (req.method === 'GET') {
    const fotoUdaraAPI = {
      "status": true,
      "message": "Success",
      "data": [
        {
          "id": 1,
          "namaData": "Foto Udara Tahun 1972",
          "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1972/ows?service=WMS",
          "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1972",
          "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
          "resolusi": "GSD 40 cm",
          "batasanPenggunaanData": "Tidak ada",
          "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
          "caraMendapatkanData": "Scanning arsip",
          "spatialsRepresentation": "EPSG 4326 / WGS 84",
          "kelengkapan": "Parsial tidak menyeluruh se DKI",
          "penjelasan":"Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
          "konsistensiLogis": "null",
          "akurasiGeometris": "Tidak dapat diukur karena data lampau",
          "akurasiTematik": "null",
          "akurasiTemporal": "Sesuai Tahun",
          "kegunaan": "Menjadi sumber data peta"
        },

        {
          "id": 2,
          "namaData": "Foto Udara Tahun 1976",
          "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1976/ows?service=WMS",
          "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1976",
          "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
          "resolusi": "GSD 80 cm",
          "batasanPenggunaanData": "Tidak ada",
          "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
          "caraMendapatkanData": "Scanning arsip",
          "spatialsRepresentation": "EPSG 4326 / WGS 84",
          "kelengkapan": "Parsial tidak menyeluruh se DKI",
          "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
          "konsistensiLogis": "null",
          "akurasiGeometris": "Tidak dapat diukur karena data lampau",
          "akurasiTematik": "null",
          "akurasiTemporal": "Sesuai Tahun",
          "kegunaan": "Menjadi sumber data peta"
        },

        {
            "id": 3,
            "namaData": "Foto Udara Tahun 1978",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1978/ows?service=WMS",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1978",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 40 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 4,
            "namaData": "Foto Udara Tahun 1979",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1979/ows?service=WMS",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1979",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 20 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "sesuai tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 5,
            "namaData": "Foto Udara Tahun 1982",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1982/ows?service=WMS",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1982",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 40 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 6,
            "namaData": "Foto Udara Tahun 1985",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1985/ows?service=WMS",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1985",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 20 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas Pemetaan dan Pengukuran Tanah",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 7,
            "namaData": "Foto Udara Tahun 1994",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1994/ows?service=WMS",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1994",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 20 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 8,
            "namaData": "Foto Udara Tahun 1994 (2)",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_1994_2/ows",
            "deskripsiData": "Foto Udara hitam putih yang diakuisisi pada tahun 1994",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 20 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Parsial tidak menyeluruh se DKI",
            "penjelasan": "Beberapa file foto udara tidak ditemukan sehingga tidak dapat dilakukan scanning dan mosaik",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Tidak dapat diukur karena data lampau",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 9,
            "namaData": "Foto Udara Tahun 2014",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_2014/ows?service=WMS",
            "deskripsiData": "Foto Udara yang diakusisi pada tahun 2014",
            "usage": "Dokumen arsip untuk melihat perubahan kondisi topografi",
            "resolusi": "GSD 25 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Arsip Dinas",
            "caraMendapatkanData": "Scanning arsip",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Jakarta bagian daratan",
            "penjelasan": "Tidak termasuk wilayah Kepulauan Seribu",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Akurasi Horizontal 1,611 m",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 10,
            "namaData": "Foto Udara Tahun 2020",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_2020/ows?service=WMS",
            "deskripsiData": "Citra Satelit Pleiades Tahun 2020 olahan BIG dengan sumber data dari LAPAN diambil di rentang tahun 2020",
            "usage": "Untuk pembuatan Peta Dasar Skala 1:5000",
            "resolusi": "GSD 50 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "LAPAN / BRIN",
            "caraMendapatkanData": "Permohonan data",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "EPSG 4326 / WGS 84",
            "konsistensiLogis": "Tidak termasuk wilayah Kepulauan Seribu",
            "akurasiGeometris": "Akurasi Horizontal 2,275 m",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 11,
            "namaData": "Foto Udara Tahun 2022",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_2022 Pleiades/ows?service=WMS",
            "deskripsiData": "Citra Satelit Pleiades dan Pleiades Neo olahan BIG dengan sumber data dari LAPAN diambil di rentang tahun 2022",
            "usage": "Untuk pembuatan Peta Dasar Skala 1:5000",
            "resolusi": "GSD 30 cm dan 50 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "LAPAN / BRIN",
            "caraMendapatkanData": "Permohonan data",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Jakarta bagian daratan",
            "penjelasan": "Tidak termasuk wilayah Kepulauan Seribu",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Akurasi Horizontal 1,669 m",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 12,
            "namaData": "Foto Udara Tahun 2022 Neo",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_2022_Neo/ows",
            "deskripsiData": "Citra Satelit Pleiades dan Pleiades Neo olahan BIG dengan sumber data dari LAPAN diambil di rentang tahun 2022",
            "usage": "Untuk pembuatan Peta Dasar Skala 1:5000",
            "resolusi": "GSD 30 cm dan 50 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "LAPAN / BRIN",
            "caraMendapatkanData": "Permohonan data",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Jakarta bagian daratan",
            "penjelasan": "Tidak termasuk wilayah Kepulauan Seribu",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Akurasi Horizontal 1,669 m",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },

          {
            "id": 13,
            "namaData": "Foto Udara Tahun 2023",
            "link": "https://gis-dev.dcktrp.id/gisimagery/dki/dki_2023/ows?service=WMS",
            "deskripsiData": "Foto Udara yang diakusisi tahun 2023 dengan wahana peswat berawak hasil kerjasama Kanwil BPN dengan Dissurpotrud TNI AU",
            "usage": "Untuk pembuatan Peta Dasar Skala 1:1000",
            "resolusi": "GSD 8 cm",
            "batasanPenggunaanData": "Tidak ada",
            "sumberData": "Akuisisi",
            "caraMendapatkanData": "Akuisisi",
            "spatialsRepresentation": "EPSG 4326 / WGS 84",
            "kelengkapan": "Jakarta bagian daratan",
            "penjelasan": "Tidak termasuk wilayah Kepulauan Seribu",
            "konsistensiLogis": "null",
            "akurasiGeometris": "Progres evaluasi data",
            "akurasiTematik": "null",
            "akurasiTemporal": "Sesuai Tahun",
            "kegunaan": "Menjadi sumber data peta"
          },
      ]
    };

    return NextResponse.json(fotoUdaraAPI);
  }
}