import { NextResponse } from "next/server";
import { ResponseError } from "../../../../../error/response-error";

export async function GET() {
  try {
    const kelurahan = [
      "Gunung Sahari Selatan",
      "Cempaka Baru",
      "Sumur Batu",
      "Petojo Selatan",
      "Kebon Kelapa",
      "Duri Pulo",
      "Pasar Baru",
      "Harapan Mulia",
      "Serdang",
      "Karang Anyar",
      "Kartini",
      "Gunung Sahari Utara",
      "Mangga Dua Selatan",
      "Kemayoran",
      "Gambir",
      "Cideng",
      "Petojo Utara",
      "Kebon Sirih",
      "Gelora",
      "Bendungan Hilir",
      "Karet Tengsin",
      "Petamburan",
      "Kebon Melati",
      "Kebon Kacang",
      "Johar Baru",
      "Kampung Rawa",
      "Galur",
      "Tanah Tinggi",
      "Penjaringan",
      "Kamal Muara",
      "Kapuk Muara",
      "Pejagalan",
      "Pluit",
      "Tanjung Priok",
      "Utan Panjang",
      "Senen",
      "Kenari",
      "Paseban",
      "Kramat",
      "Kwitang",
      "Bungur",
      "Cempaka Putih Timur",
      "Rawasari",
      "Menteng",
      "Pegangsaan",
      "Cikini",
      "Gondangdia",
      "Kelapa Gading Timur",
      "Pegangsaan Dua",
      "Kelapa Gading Barat",
      "Cengkareng Barat",
      "Duri Kosambi",
      "Rawa Buaya",
      "Kedaung Kali Angke",
      "Kapuk",
      "Cengkareng Timur",
      "Jati Padang",
      "Lagoa",
      "Rawa Badak Utara",
      "Tugu Selatan",
      "Rawa Badak Selatan",
      "Sukapura",
      "Marunda",
      "Sunter Jaya",
      "Papanggo",
      "Sungai Bambu",
      "Kebon Bawang",
      "Sunter Agung",
      "Warakas",
      "Koja",
      "Tugu Utara",
      "Kalibaru",
      "Semper Timur",
      "Rorotan",
      "Pademangan Timur",
      "Pademangan Barat",
      "Grogol",
      "Tomang",
      "Ancol",
      "Duri Utara",
      "Tanah Sereal",
      "Krendang",
      "Angke",
      "Jembatan Lima",
      "Pekojan",
      "Roa Malaka",
      "Duri Selatan",
      "Kebon Jeruk",
      "Sukabumi Utara",
      "Jelambar",
      "Tanjung Duren Selatan",
      "Jelambar Baru",
      "Wijaya Kusuma",
      "Taman Sari",
      "Krukut",
      "Maphar",
      "Tangki",
      "Mangga Besar",
      "Glodok",
      "Pinangsia",
      "Tambora",
      "Kali Anyar",
      "Tebet Barat",
      "Menteng Dalam",
      "Kota Bambu Utara",
      "Jatipulo",
      "Kramat Pela",
      "Selong",
      "Sukabumi Selatan",
      "Kelapa Dua",
      "Duri Kepa",
      "Kedoya Utara",
      "Kedoya Selatan",
      "Kalideres",
      "Semanan",
      "Tegal Alur",
      "Kamal",
      "Pegadungan",
      "Palmerah",
      "Slipi",
      "Kemanggisan",
      "Kota Bambu Selatan",
      "Kembangan Utara",
      "Meruya Utara",
      "Meruya Selatan",
      "Srengseng",
      "Joglo",
      "Kembangan Selatan",
      "Kebon Baru",
      "Tebet Timur",
      "Kuningan Timur",
      "Mampang Prapatan",
      "Bangka",
      "Pela Mampang",
      "Tegal Parang",
      "Kuningan Barat",
      "Pasar Minggu",
      "Cilandak Timur",
      "Ragunan",
      "Pejaten Timur",
      "Kebagusan",
      "Kebayoran Lama Utara",
      "Cipulir",
      "Grogol Utara",
      "Grogol Selatan",
      "Kebayoran Lama Selatan",
      "Cilandak Barat",
      "Lebak Bulus",
      "Rawa Barat",
      "Senayan",
      "Pulo",
      "Petogogan",
      "Gandaria Utara",
      "Bukit Duri",
      "Manggarai Selatan",
      "Manggarai",
      "Setia Budi",
      "Karet Semanggi",
      "Karet Kuningan",
      "Karet",
      "Menteng Atas",
      "Pasar Manggis",
      "Guntur",
      "Rawamangun",
      "Pulo Gadung",
      "Petukangan Selatan",
      "Ulujami",
      "Pisangan Baru",
      "Pisangan Timur",
      "Cipete Utara",
      "Pancoran",
      "Kalibata",
      "Rawajati",
      "Duren Tiga",
      "Pengadegan",
      "Cikoko",
      "Jagakarsa",
      "Srengseng Sawah",
      "Ciganjur",
      "Lenteng Agung",
      "Tanjung Barat",
      "Cipedak",
      "Pesanggrahan",
      "Bintaro",
      "Petukangan Utara",
      "Pondok Labu",
      "Gandaria Selatan",
      "Melawai",
      "Gunung",
      "Kebon Manggis",
      "Utan Kayu Selatan",
      "Cipinang",
      "Jatinegara Kaum",
      "Cipinang Besar Selatan",
      "Cipinang Besar Utara",
      "Kramatjati",
      "Dukuh",
      "Batu Ampar",
      "Balekambang",
      "Cililitan",
      "Cawang",
      "Gedong",
      "Baru",
      "Cijantung",
      "Kalisari",
      "Pekayon",
      "Jatinegara",
      "Rawa Terate",
      "Penggilingan",
      "Cakung Timur",
      "Pulo Gebang",
      "Ujung Menteng",
      "Cakung Barat",
      "Duren Sawit",
      "Pondok Bambu",
      "Klender",
      "Pondok Kelapa",
      "Malaka Sari",
      "Malaka Jaya",
      "Utan Kayu Utara",
      "Kayu Manis",
      "Palmeriam",
      "Lubang Buaya",
      "Ceger",
      "Kayu Putih",
      "Jati",
      "Kampung Melayu",
      "Bidara Cina",
      "Bali Mester",
      "Rawa Bunga",
      "Cipinang Cempedak",
      "Cipinang Muara",
      "Keagungan",
      "Pinangranti",
      "Bambu Apus",
      "Kampung Bali",
      "Pondok Pinang",
      "Pulau Harapan",
      "Pulau Panggang",
      "Pulau Pari",
      "Pulau Tidung",
      "Pulau Kelapa",
      "Pulau Untung Jawa",
      "Kebon Kosong",
      "Tengah",
      "Tanjung Duren Utara",
      "Pejaten Barat",
      "Cipete Selatan",
      "Kelapa Dua Wetan",
      "Pondok Kopi",
      "Makasar",
      "Kebon Pala",
      "Halim Perdana Kusuma",
      "Cipinang Melayu",
      "Ciracas",
      "Cibubur",
      "Susukan",
      "Rambutan",
      "Cipayung",
      "Cilangkap",
      "Pondok Ranggon",
      "Munjul",
      "Setu",
      "Cempaka Putih Barat",
      "Jembatan Besi",
      "Cilincing",
      "Semper Barat",
    ];

    return NextResponse.json(kelurahan, { status: 200 });
  } catch (error) {
    if (error instanceof ResponseError) {
      return new NextResponse(JSON.stringify({ errors: error.message }), {
        status: error.status,
        headers: { "Content-Type": "application/json" },
      });
    } else {
      console.error(error);
      return new NextResponse(
        JSON.stringify({ errors: "Internal Server Error" }),
        {
          status: 500,
          headers: { "Content-Type": "application/json" },
        }
      );
    }
  }
}
