import { NextResponse } from "next/server";

export async function GET(req) {
    if (req.method === 'GET') {
        const eventAPI =
            [
                {
                    "id": 1,
                    "slug": "jakarta-satu-festival-2023-1",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Timur",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Timur",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci."
                    ],
                },
                {
                    "id": 2,
                    "slug": "pekan-raya-jakarta-2023-1",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Barat",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Barat",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 3,
                    "slug": "event-ke3-1",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Selatan",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 4,
                    "slug": "pekan-raya-jakarta-2023-2",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Pusat",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Pusat",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 5,
                    "slug": "jakarta-satu-festival-2023-2",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Utara",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Utara",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 6,
                    "slug": "event-ke3-2",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Utara",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Utara",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 7,
                    "slug": "pekan-raya-jakarta-2023-3",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Timur",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Timur",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 8,
                    "slug": "event-ke3-3",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Pusat",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Pusat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 9,
                    "slug": "jakarta-satu-festival-2023-3",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Barat",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Barat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 10,
                    "slug": "jakarta-satu-festival-2023-4",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Utara",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Utara",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 11,
                    "slug": "pekan-raya-jakarta-2023-4",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Selatan",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 12,
                    "slug": "event-ke3-4",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Selatan",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 13,
                    "slug": "pekan-raya-jakarta-2023-5",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Timur",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Timur",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 14,
                    "slug": "jakarta-satu-festival-2023-5",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Timur",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Timur",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 15,
                    "slug": "event-ke3-5",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Barat",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Barat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 16,
                    "slug": "pekan-raya-jakarta-2023-6",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Utara",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Utara",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 17,
                    "slug": "event-ke3-6",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Selatan",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 18,
                    "slug": "jakarta-satu-festival-2023-6",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Selatan",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 19,
                    "slug": "jakarta-satu-festival-2023-7",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Barat",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Barat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 20,
                    "slug": "pekan-raya-jakarta-2023-7",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Pusat",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Pusat",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 21,
                    "slug": "event-ke3-7",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Utara",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Utara",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 22,
                    "slug": "pekan-raya-jakarta-2023-8",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Timur",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Timur",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 23,
                    "slug": "jakarta-satu-festival-2023-8",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Selatan",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 24,
                    "slug": "event-ke3-8",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Barat",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Barat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 25,
                    "slug": "pekan-raya-jakarta-2023-9",
                    "namaData": "Pekan Raya Jakarta 2023",
                    "kategori": "Makan & Minuman",
                    "wilayah": "Jakarta Selatan",
                    "imgSrc": "/assets/Makanan-Minuman.jpg",
                    "tanggal": "01 Januari 2023 - 31 Januari 2023",
                    "pukul": "06:00 - 12:00",
                    "lokasi": "Kemayoran, Jakarta Selatan",
                    "linkWeb": "https://jakartafair.co.id/",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 26,
                    "slug": "event-ke3-9",
                    "namaData": "Event Ke 3",
                    "kategori": "Sains & Teknologi",
                    "wilayah": "Jakarta Pusat",
                    "imgSrc": "/assets/Teknologi.jpg",
                    "tanggal": "01 Februari 2023 - 31 Februari 2023",
                    "pukul": "04:00 - 10:00",
                    "lokasi": "Kemayoran, Jakarta Pusat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/web",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
                {
                    "id": 27,
                    "slug": "jakarta-satu-festival-2023-9",
                    "namaData": "Jakarta Satu Festival 2023",
                    "kategori": "Pertunjukkan & Seni Visual",
                    "wilayah": "Jakarta Pusat",
                    "imgSrc": "/assets/Karya-Seni.jpg",
                    "tanggal": "01 Oktober 2023 - 31 Oktober 2023",
                    "pukul": "08:00 - 16:00",
                    "lokasi": "Cideng, Jakarta Pusat",
                    "linkWeb": "https://jakartasatu.jakarta.go.id/festival",
                    "deskripsi": [
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                        "Lorem ipsum dolor sit amet consectetur. Turpis volutpat cursus sit odio orci.",
                    ],
                },
            ]

        return NextResponse.json(eventAPI)
    }
}